WaveAccountingIntegration/Controllers/BusinessProcessingMahayagController.cs
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics.Eventing.Reader;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Xml.Schema;
using Microsoft.Ajax.Utilities;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using WaveAccountingIntegration.Models;


namespace WaveAccountingIntegration.Controllers
{
	public class BusinessProcessingMahayagController : BaseController
	{
        private int MAX_LATE_LOCATIONS_ALERTS = 3;
        private int MAX_TRASH_LOCATIONS_ALERTS = 3;
        public ActionResult AutoPinResetAndText(DayOfWeek day = DayOfWeek.Sunday)
		{
			var messages = new ConcurrentBag<string>();
			var testDateString = "2018-09-22";

			if (DateTime.Today.Date <= DateTime.Parse(testDateString))
				day = DayOfWeek.Saturday;

			if (DateTime.Today.DayOfWeek == day && DateTime.Now.Hour < 14 && DateTime.Now.Hour > 8)
			{
				var propertyIds = _appSettings.MahayagAddresses.Select(x => x.Id);

				if (DateTime.Today.Date >= DateTime.Parse(testDateString))
					propertyIds = propertyIds.Where(x => x == "0000");

				var allActiveCustomers = GetActiveCustomers();

				//Parallel.ForEach(propertyIds, id =>
				//{
				foreach (var id in propertyIds.ToList())
				{

					var customersAtThisAddress = allActiveCustomers.Where(x => x.name.StartsWith(id));
					var customerSettingsAtThisAddress = new Dictionary<Customer, CustomerSettings>();

					foreach (var cust in customersAtThisAddress.ToList())
					{
						customerSettingsAtThisAddress.Add(cust, _customerService.ExctractSettingsFromCustomerObject(cust));
					}

					//check if someoene got their pin reset today
					var pinResetsToday = customerSettingsAtThisAddress.Where(x => x.Value.LastPinResetDate?.Date == DateTime.Today.Date);
					if (pinResetsToday.Any())
					{
						messages.Add($"Pin reset for customer:{pinResetsToday.First().Key.name} already occured today on preperty Id: {id};");
					}
					else
					{
						var customer = customerSettingsAtThisAddress.OrderBy(x => x.Value.LastPinResetDate).First().Key;
						var custSettings = _customerService.ExctractSettingsFromCustomerObject(customer);

						if (custSettings.LastPinResetDate >= DateTime.Today.Date.AddMonths(-1))
						{
							messages.Add($"Skipping Pin reset for customer:{pinResetsToday.First().Key.name} since it already occured on {custSettings.LastPinResetDate}, and is less than a month ago");
						}
						else
						{
							custSettings.LastPinResetDate = DateTime.Today;

							var newPin = new Random().Next(0000, 9919).ToString("0000");
							var oldPin = customer.phone_number;

							if (_customerService.SaveUpdatedCustomerSettings(customer, custSettings, _restService).IsSuccessStatusCode)
							{
								if (_customerService.SaveUpdatedCustomerPhone(customer, newPin, _restService).IsSuccessStatusCode)
								{
									//sent alert to name 1
									if (!string.IsNullOrWhiteSpace(ExtractEmailFromString(customer.address1)))
									{
										var name = customer.first_name ?? "".ToUpper().Trim();
										var body = GetAutoPinResetAndTextSmsAlertBody(name, oldPin, newPin);

										messages.Add($"alerting new/old pin: {newPin}/{oldPin} for customer:{name} on {ExtractEmailFromString(customer.address1)}");
										_sendGmail.SendSMS(ExtractEmailFromString(customer.address1), body, _appSettings.GoogleSettings);
									}

									//sent alert to name 2
									if (!string.IsNullOrWhiteSpace(ExtractEmailFromString(customer.address2)))
									{
										var name = customer.last_name?? "".ToUpper().Trim();
										var body = GetAutoPinResetAndTextSmsAlertBody(name, oldPin, newPin);

										messages.Add($"alerting new/old pin: {newPin}/{oldPin} for customer:{name} on {ExtractEmailFromString(customer.address1)}");
										_sendGmail.SendSMS(ExtractEmailFromString(customer.address2), body, _appSettings.GoogleSettings);
									}
								}
							}
						}
						
					}

				}
				//});
			}
			else
			{
				messages.Add($"Skip Pin Reset since DateTime.Now.Hour={DateTime.Now.Hour}; DateTime.Today.DayOfWeek={DateTime.Today.DayOfWeek.ToString()};");
			}

			ViewBag.Message = string.Join(Environment.NewLine, messages);
			return View();
		}

		public ActionResult SmsAlertLateCustomers(int daysBetweenAlerts = 3, ulong narrowByCustomerId = 0)
		{
			var lateCustomers = Customers(narrowByCustomerId);
			var messages = new ConcurrentBag<string>();

			var customersWithBalance = lateCustomers.Where(w => w.Value.ending_balance > 0);
            var counter = 1;
			//Parallel.ForEach(customersWithBalance, (customerKvp) =>
			foreach(var customerKvp in customersWithBalance)
			{
				var customer = customerKvp.Key;
				var custSettings = _customerService.ExctractSettingsFromCustomerObject(customer);

				var daysSinceLastSmsAlert = (DateTime.Now - (custSettings.LastSmsAlertSent?? DateTime.Now)).Days;

				var minDaysBetweenAlerts = Math.Max(custSettings.CustomDaysBetweenSmsAlerts?? daysBetweenAlerts, daysBetweenAlerts);

				var lastPayment = customerKvp.Value.events.Where(x => x.event_type == "payment").OrderByDescending(x => x.date).FirstOrDefault();
				var lastInvoice = customerKvp.Value.events.Where(x => x.event_type == "invoice" && x.total > 0).OrderByDescending(x => x.date).First();
				var invoiceDue = _restService.Get<Invoice>(lastInvoice.invoice.url).Result;
				var daysSinceLastPayment = (DateTime.Now - (lastPayment?.date?? DateTime.Now.AddYears(-10))).Days;

				if (
					daysSinceLastSmsAlert >= minDaysBetweenAlerts &&
					daysSinceLastPayment >= 5 &&
					(lastInvoice.date <= DateTime.Today.Date.AddDays(-5) || lastInvoice.date <= DateTime.Today.Date.AddDays(-10)) &&
					DateTime.Now.Hour >= 8 &&
					DateTime.Now.Hour < 21 &&
					//DateTime.Now.DayOfWeek != DayOfWeek.Saturday &&
					//DateTime.Now.DayOfWeek != DayOfWeek.Sunday &&
					custSettings.SendSmsAlerts == true &&
					customerKvp.Value.ending_balance >= 35
				)
				{
					//sent alert to name 1
					if (!string.IsNullOrWhiteSpace(ExtractEmailFromString(customer.address1)))
					{
						var mainName = customer.first_name?? "".ToUpper().Trim();

						if (!mainName.Contains(";"))
						{
							var body = GetLateCustomerSmsAlertBody(mainName, customerKvp, lastPayment, invoiceDue, custSettings);

							messages.Add($"alerting late customer:{mainName} on {ExtractEmailFromString(customer.address1)}");
							_sendGmail.SendSMS(ExtractEmailFromString(customer.address1), body, _appSettings.GoogleSettings);
						}
						else
						{
							var names = mainName.Split(';');
							var emails = customer.address1.Split(';');

							var i = 0;
							foreach(var name in names)
							{
								var body = GetLateCustomerSmsAlertBody(name.Trim(), customerKvp, lastPayment, invoiceDue, custSettings);

								var email = emails[i];
								i++;

								messages.Add($"alerting late customer:{name.Trim()} on {ExtractEmailFromString(email)}");
								_sendGmail.SendSMS(ExtractEmailFromString(email), body, _appSettings.GoogleSettings);
							}
						}
					}

					//sent alert to name 2
					if (!string.IsNullOrWhiteSpace(ExtractEmailFromString(customer.address2)))
					{
						var mainName = customer.last_name ?? "".ToUpper().Trim();

						if (!mainName.Contains(";"))
						{
							var body = GetLateCustomerSmsAlertBody(mainName, customerKvp, lastPayment, invoiceDue, custSettings);

							messages.Add($"alerting late customer: {mainName} on {ExtractEmailFromString(customer.address2)}");
							_sendGmail.SendSMS(ExtractEmailFromString(customer.address2), body, _appSettings.GoogleSettings);
						}
						else
						{
							var names = mainName.Split(';');
							var emails = customer.address2.Split(';');

							var i = 0;
							foreach (var name in names)
							{
								var body = GetLateCustomerSmsAlertBody(name.Trim(), customerKvp, lastPayment, invoiceDue, custSettings);

								var email = emails[i];
								i++;

								messages.Add($"alerting late customer:{name.Trim()} on {ExtractEmailFromString(email)}");
								_sendGmail.SendSMS(ExtractEmailFromString(email), body, _appSettings.GoogleSettings);
							}
						}
					}

                    //sent alerts to supplemantal shipping names 
                    if (!string.IsNullOrWhiteSpace(customer.shipping_details.city))
                    {
                        var names = customer.shipping_details.city.Split(';');
                        var emails = 
                            (customer.shipping_details.address1 + 
                            (string.IsNullOrWhiteSpace(customer.shipping_details.address2) ? "" : $"; {customer.shipping_details.address2}")
                            ).Split(';').Take(names.Count()).ToList();

                        var i = 0;
                        foreach (var name in names)
                        {
                            var body = GetLateCustomerSmsAlertBody(name.Trim(), customerKvp, lastPayment, invoiceDue, custSettings);

                            var email = emails[i];
                            i++;

                            messages.Add($"alerting late customer:{name.Trim()} on {ExtractEmailFromString(email)}");
                            _sendGmail.SendSMS(ExtractEmailFromString(email), body, _appSettings.GoogleSettings);
                        }
                    }

					custSettings.LastSmsAlertSent = DateTime.Now;
					_customerService.SaveUpdatedCustomerSettings(customer, custSettings, _restService);

                    if(++counter > MAX_LATE_LOCATIONS_ALERTS)
                    {
                        messages.Add($"Skipping rest as counter {counter} > {MAX_LATE_LOCATIONS_ALERTS}");
                        break;
                    }
				}
				else
				{
					//skip alert

WaveAccountingIntegration/Views/BusinessProcessingMahayag/5DayTennantAtWill.cshtml
@model Dictionary<WaveAccountingIntegration.Models.Customer, WaveAccountingIntegration.Models.Transaction_History>

@{
	Layout = null;

	var entry = Model.First();

	List<WaveAccountingIntegration.Models.Tennant> tenants = ViewBag.Tenants;

	Common.Models.Address address = ViewBag.address;
}


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="utf-8"/>

	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
	<link rel="stylesheet" href="/Content/forms/5DayTennantAtWill/base.min.css"/>
	<link rel="stylesheet" href="/Content/forms/5DayTennantAtWill/fancy.min.css"/>
	<link rel="stylesheet" href="/Content/forms/5DayTennantAtWill/main.css"/>
	<script src="/Content/forms/5DayTennantAtWill/compatibility.min.js"></script>
	<script src="/Content/forms/5DayTennantAtWill/theViewer.min.js"></script>
	<script>
try{
	theViewer.defaultViewer = new theViewer.Viewer({});
}catch(e){}
	</script>
	<title>@ViewBag.Title</title>
</head>
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<div id="sidebar">
	<div id="outline"></div>
</div>
<div id="page-container">
@foreach (var t in tenants)
{
	<div class="pf w0 h0" data-page-no="1" id="pf1">
<div class="pc pc1 w0 h0">
	<img alt="" class="bi x0 y0 w0 h0" src="/Content/forms/5DayTennantAtWill/bg1.png">
	<div class="t m0 x3 h3 y3 ff3 fs1 fc1 sc0 ls0 ws0">
FIVE DAY N<span class="_ _0"></span>OTICE TO A TEN<span class="_ _0"></span>ANT AT WILL
	</div>
	<div class="t m0 x4 h4 y4 ff4 fs2 fc1 sc0 ls0 ws0">
This Notice is given to: <span class="_ _2"></span>This Notice is given by:
	</div>
	<div class="t m0 x5 h5 y5 ff5 fs2 fc1 sc0 ls0 ws0">
@t.FullName
	</div>
	<div class="t m0 x5 h5 y6 ff5 fs2 fc1 sc0 ls0 ws0">
@address.Address1
	</div>
	<div class="t m0 x5 h5 y7 ff5 fs2 fc1 sc0 ls0 ws0">
@address.City, @address.State @address.ZipCode
	</div>
	<div class="t m0 x6 h5 y5 ff5 fs2 fc1 sc0 ls0 ws0">
Todor Peykov
	</div>
	<div class="t m0 x6 h5 y6 ff5 fs2 fc1 sc0 ls0 ws0">
PO BOX 271157
	</div>
	<div class="t m0 x6 h5 y7 ff5 fs2 fc1 sc0 ls0 ws0">
Salt Lake City, UT 84127-
	</div>
	<div class="t m0 x4 h5 y8 ff5 fs2 fc1 sc0 ls0 ws0">
You are a tenant at will. You are required to vacate the prem<span class="_ _0"></span>ises within five calendar
	</div>
	<div class="t m0 x4 h5 y9 ff5 fs2 fc1 sc0 ls0 ws0">
days, counting weekends an<span class="_ _1"></span>d holidays.
	</div>
	<div class="t m0 x4 h4 ya ff4 fs2 fc1 sc0 ls0 ws0">
If you do not comply with this notice, you will be served with a Summons and Complaint for
	</div>
	<div class="t m0 x4 h4 yb ff4 fs2 fc1 sc0 ls0 ws0">
unlawful detainer. Unlawful detainer is when you remain in possession of rental property after
	</div>
	<div class="t m0 x4 h4 yc ff4 fs2 fc1 sc0 ls0 ws0">
the owner serves you with a lawful notice to leave, such as this eviction notice. If you are found
	</div>
	<div class="t m0 x4 h4 yd ff4 fs2 fc1 sc0 ls0 ws0">
by the court to be in unlawful detainer, you will be evicted by the court and you will be liable for:
	</div>
	<div class="t m0 x4 h4 ye ff4 fs2 fc1 sc0 ls0 ws0">
1. any rent due and unpaid through the end of your rental agreement, less any amounts the
	</div>
	<div class="t m0 x4 h4 yf ff4 fs2 fc1 sc0 ls0 ws0">
landlord receives from the next tenant;
	</div>
	<div class="t m0 x4 h4 y10 ff4 fs2 fc1 sc0 ls0 ws0">
2. damages ca<span class="_ _0"></span>used by<span class="_ _0"></span> y<span class="_ _0"></span>our unlawful detainer<span class="_ _0"></span> of the rental property<span class="_ _3"></span>;
	</div>
	<div class="t m0 x4 h4 y11 ff4 fs2 fc1 sc0 ls0 ws0">
3. damages for any waste of the rental property caused by you, if and only if the landlord alleges
	</div>
	<div class="t m0 x4 h4 y12 ff4 fs2 fc1 sc0 ls0 ws0">
them in a court complaint and proves them at trial, or submits them to the court by affidavit in
	</div>
	<div class="t m0 x4 h4 y13 ff4 fs2 fc1 sc0 ls0 ws0">
the event of y<span class="_ _0"></span>our de<span class="_ _0"></span>fault (Waste is damage y<span class="_ _0"></span>ou caus<span class="_ _0"></span>e bey<span class="_ _0"></span>ond normal wea<span class="_ _0"></span>r and tear.);
	</div>
	<div class="t m0 x4 h4 y14 ff4 fs2 fc1 sc0 ls0 ws0">
4. damages as provide<span class="_ _0"></span>d in Utah Code 78B-6-1107 throug<span class="_ _0"></span>h 1114 for the abatement of nuisa<span class="_ _0"></span>nce,
	</div>
	<div class="t m0 x4 h4 y15 ff4 fs2 fc1 sc0 ls0 ws0">
if any<span class="_ _0"></span>, caused by<span class="_ _0"></span> y<span class="_ _0"></span>ou. (<span class="_ _0"></span>Abatement of nuisance means to stop a nuisance<span class="_ _0"></span>.);
	</div>
	<div class="t m0 x4 h4 y16 ff4 fs2 fc1 sc0 ls0 ws0">
5. attorney<span class="_ _0"></span>s fee<span class="_ _0"></span>s and court costs.
	</div>
	<div class="t m0 x4 h4 y17 ff4 fs2 fc1 sc0 ls0 ws0">
You will also be liable for three<span class="_ _0"></span> times those damages allowed to be tre<span class="_ _0"></span>bled under Utah Code
	</div>
	<div class="t m0 x4 h4 y18 ff4 fs2 fc1 sc0 ls0 ws0">
78B-6-811 which specifically may include trebling all of those damages mentioned above except
	</div>
	<div class="t m0 x4 h4 y19 ff4 fs2 fc1 sc0 ls0 ws0">
attorney<span class="_ _0"></span>s fee<span class="_ _0"></span>s and court costs. Damage<span class="_ _0"></span>s under (2) are the r<span class="_ _0"></span>easonable rental value or r<span class="_ _0"></span>easonable
	</div>
	<div class="t m0 x4 h4 y1a ff4 fs2 fc1 sc0 ls0 ws0">
value of the use and occupation of the premises for each day you remain after the expiration of
	</div>
	<div class="t m0 x4 h4 y1b ff4 fs2 fc1 sc0 ls0 ws0">
this notice. In most cases trebling damages under (2) means the court will times the amount you
	</div>
	<div class="t m0 x4 h4 y1c ff4 fs2 fc1 sc0 ls0 ws0">
have been pay<span class="_ _3"></span>ing for r<span class="_ _0"></span>ent by<span class="_ _0"></span> three for every<span class="_ _0"></span> da<span class="_ _0"></span>y<span class="_ _0"></span> y<span class="_ _0"></span>ou remain in the property<span class="_ _0"></span> a<span class="_ _0"></span>fter the last day<span class="_ _0"></span> y<span class="_ _0"></span>ou
	</div>
	<div class="t m0 x4 h4 y1d ff4 fs2 fc1 sc0 ls0 ws0">
were given to leave under this eviction notice. Please contact your landlord to discuss this
	</div>
	<div class="t m0 x4 h4 y1e ff4 fs2 fc1 sc0 ls0 ws0">
situation.
	</div>
	<div class="t m0 x7 h4 y1f ff4 fs2 fc1 sc0 ls0 ws0">
Date @DateTime.Now.ToUSADateFormat() <span class="_ _4"></span>Sign here <img src="~/Content/Images/tp_sig.png"/> /s/ Todor Peykov
	</div>
	<div class="t m0 x8 h5 y20 ff5 fs2 fc1 sc0 ls0 ws0">

	</div>
	<div class="t m0 x4 h1 y21 ff6 fs3 fc1 sc0 ls0 ws0">
@DateTime.Now.ToUSADateFormat()<span class="_ _1"></span> <span class="_ _5"></span>Five Day Notice to Vacate to Tenant at Will <span class="_ _6"></span>Page <span class="ff1 fs0">1</span>
	</div>
</div>
<div class="pi" data-data='{"ctm":[1.000000,0.000000,0.000000,1.000000,0.000000,0.000000]}'></div>
	</div>
	<div class="pf w0 h0" data-page-no="2" id="pf2">
<div class="pc pc2 w0 h0">
	<img alt="" class="bi x0 y0 w0 h0" src="/Content/forms/5DayTennantAtWill/bg2.png">
	<div class="t m0 x1 h1 y1 ff1 fs0 fc0 sc0 ls0 ws0">
<span class="_ _0"></span><span class="_ _1"></span>
	</div>
	<div class="t m0 x9 h5 y22 ff5 fs2 fc1 sc0 ls0 ws0">
RETURN OF SERVICE
	</div>
	<div class="t m0 x4 h4 y23 ff4 fs2 fc1 sc0 ls0 ws0">
This Notice was served upon <span class="ff5">@t.FullName</span>, on @DateTime.Now.ToUSADateFormat() <span class="ff7 fs0">(date)</span> in the following
	</div>
	<div class="t m0 x4 h4 y24 ff4 fs2 fc1 sc0 ls0 ws0">
manner:
	</div>
	<div class="t m0 x4 h5 y25 ff5 fs2 fc1 sc0 ls0 ws0">
(Please chec<span class="_ _0"></span>k the appropriate boxes.)
	</div>
	<div class="t m0 x4 h4 y26 ff2 fs0 fc1 sc0 ls0 ws0">
[X] <span class="ff1"><span class="ff4 fs2">A copy<span class="_ _0"></span> was deliver<span class="_ _0"></span>ed to the tenant personally<span class="_ _0"></span>.</span></span>
	</div>
	<div class="t m0 x4 h4 y27 ff2 fs0 fc1 sc0 ls0 ws0">
[_] <span class="ff1"><span class="ff4 fs2">A copy was sent through certified or registered mail to the tenant <span class="_ _7"></span>s address.</span></span>
	</div>
	<div class="t m0 x4 h4 y28 ff2 fs0 fc1 sc0 ls0 ws0">
[X] <span class="ff1"><span class="ff4 fs2">A copy<span class="_ _0"></span> was posted in a c<span class="_ _0"></span>onspicuous place on the premises, as no one was<span class="_ _0"></span> home.</span></span>
	</div>
	<div class="t m0 x4 h4 y29 ff2 fs0 fc1 sc0 ls0 ws0">
[_] <span class="ff1"><span class="ff4 fs2">A copy<span class="_ _0"></span> was left with __________________ a pe<span class="_ _0"></span>rson of suitable age a<span class="_ _0"></span>nd discretion at:</span></span>
	</div>
	<div class="t m0 x7 h4 y2a ff2 fs0 fc1 sc0 ls0 ws0">
[_] <span class="ff1"><span class="ff4 fs2">tenant <span class="_ _7"></span>s residence or</span></span>
	</div>
	<div class="t m0 x7 h4 y2b ff2 fs0 fc1 sc0 ls0 ws0">
[_] <span class="ff1"><span class="ff4 fs2">tenant&apos;s place of business</span></span>
	</div>
	<div class="t m0 x7 h4 y2c ff4 fs2 fc1 sc0 ls0 ws0">
AND a second copy<span class="_ _0"></span> w<span class="_ _0"></span>as mailed to
	</div>
	<div class="t m0 xa h4 y2d ff2 fs0 fc1 sc0 ls0 ws0">
[_] <span class="ff1"><span class="ff4 fs2">tenant <span class="_ _7"></span>s residence or</span></span>
	</div>
	<div class="t m0 xa h4 y2e ff2 fs0 fc1 sc0 ls0 ws0">
[_] <span class="ff1"><span class="ff4 fs2">place of business.</span></span>
	</div>
	<div class="t m0 xb h4 y2f ff4 fs2 fc1 sc0 ls0 ws0">
Sign here <img src="~/Content/Images/tp_sig.png"/> /s/ Todor Peykov
	</div>
	<div class="t m0 xc h4 y30 ff4 fs2 fc1 sc0 ls0 ws0">

	</div>
	<div class="t m0 x4 h1 y21 ff6 fs3 fc1 sc0 ls0 ws0">
@DateTime.Now.ToUSADateFormat()<span class="_ _1"></span> <span class="_ _5"></span>Five Day Notice to Vacate to Tenant at Will <span class="_ _6"></span>Page <span class="ff1 fs0">2</span>
	</div>
</div>
<div class="pi" data-data='{"ctm":[1.000000,0.000000,0.000000,1.000000,0.000000,0.000000]}'></div>
	</div>
}
</div>
<div class="loading-indicator"></div>
</body>
</html>
</html>

WaveAccountingIntegration/Views/BusinessProcessingMahayag/AutoPinResetAndtext.cshtml
@{
	Layout = null;

	ViewBag.Title = "AutoPinResetAndText";

	string Message = ViewBag.Message;
}

<h2>AutoPinResetAndText</h2>

<div>
	@{
		Html.RenderPartial("Pre", Message);
	}
</div>

WaveAccountingIntegration/Views/BusinessProcessingMahayag/BroadcastMessage.cshtml
@{
	Layout = null;
	ViewBag.Title = "BroadcastMessage";

	string Message = ViewBag.Message;
}
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>BroadcastMessage</title>
</head>
<body>


	@if (ViewBag.displayForm == true)
	{
		using (Html.BeginForm("BroadcastMessage", "BusinessProcessingMahayag"))
		{
			<div>
				Message *:
				<p>
					@Html.TextArea("message")
				</p>
			</div>
			<div>
				nameStartsWith parts separated by ',':
				<p>
					@Html.TextBox("nameStartsWith")
				</p>
			</div>
			<div>
				excludeStartsWith parts separated by ',':
				<p>
					@Html.TextBox("excludeStartsWith")
				</p>
			</div>
			<div>
				excludeContains parts separated by ',':
				<p>
					@Html.TextBox("excludeContains")
				</p>
			</div>

			<p>
				<button type="submit" class="btn btn-default" id="submit">submit</button>
			</p>
		}
	}
	else
	{
		<h2>BroadcastMessage</h2>

		<div>
			@{
				Html.RenderPartial("Pre", Message);
			}
		</div>

	}



</body>
</html>

WaveAccountingIntegration/Views/BusinessProcessingMahayag/BrodcastAlertCustomers.cshtml
@{
	Layout = null;
	ViewBag.Title = "BrodcastAlertCustomers";

	string Message = ViewBag.Message;
}
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>LateCustomers</title>
</head>
<body>


	@if (ViewBag.displayForm == true)
	{
		using (Html.BeginForm("BrodcastAlertCustomers", "BusinessProcessingMahayag"))
		{
			<div>
				Message*:
				<p>
					@Html.TextArea("message")
				</p>
			</div>
			<div>
				nameStartsWith:
				<p>
					@Html.TextBox("nameStartsWith")
				</p>
			</div>



			<p>
				<button type = "submit" class="btn btn-default" id="submit">submit</button>
			</p>
		}
	}
	else
	{
		<h2>BrodcastAlertCustomers</h2>

		<div>
			@{
				Html.RenderPartial("Pre", Message);
			}
		</div>

	}



</body>
</html>

WaveAccountingIntegration/Views/BusinessProcessingMahayag/DisableInvoicePayments.cshtml
@model IEnumerable<WaveAccountingIntegration.Models.Invoice>

@{
	Layout = null;
	
	ViewBag.Title = "DisableInvoicePayments";

	string Message = ViewBag.Message;
}

<h2>DisableInvoicePayments</h2>

<div>
	@{
		Html.RenderPartial("Pre", Message);
	}
</div>

WaveAccountingIntegration/Views/BusinessProcessingMahayag/SmsAlertLateCustomers.cshtml
@{
	Layout = null;

	ViewBag.Title = "SmsAlertLateCustomers";

	string Message = ViewBag.Message;
}

<h2>SmsAlertLateCustomers</h2>

<div>
	@{
		Html.RenderPartial("Pre", Message);
	}
</div>